# This file shall contain routes used to build URLs that are defined within the
# application. Routes that are not served by this application should be stored
# in routing_3rd_party.yml. This includes routes that will eventually be served
# by this application but have not yet been migrated

status:
    path: /status
    defaults: { _controller: App\Controller\StatusController }

root:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: home, permanent: true }

home:
    path: /programmes
    defaults: { _controller: App\Controller\HomeController }

find_by_pid:
    path: /programmes/{pid}
    # !find_by_pid is a special value, that shall be converted into an proper
    # _controller value (i.e. a class name) by the FindByPidRouterSubscriber
    defaults: { _controller: '!find_by_pid' }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}' }

schedules_home:
    path: /schedules
    defaults: { _controller: App\Controller\SchedulesHomeController }

schedules_by_day:
    path: /schedules/{pid}/{date}
    defaults: { _controller: App\Controller\SchedulesByDayController, date: null }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', date: '\d{4}/\d{2}/\d{2}' }

schedules_by_week:
    path: /schedules/{pid}/{date}
    defaults: { _controller: App\Controller\SchedulesByWeekController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', date: '\d{4}/w([0-4][0-9]|[5][0-3])' }

schedules_by_month:
    path: /schedules/{pid}/{date}
    defaults: { _controller: App\Controller\SchedulesByMonthController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', date: '\d{4}/\d{2}' }

schedules_by_vanity:
    path: /schedules/{pid}/{vanity}
    defaults: { _controller: App\Controller\SchedulesVanityRedirectController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', vanity: 'yesterday|today|tomorrow|(?:this|next|last)_(?:week|month)' }

schedules_by_year:
    path: /schedules/{pid}/{year}
    defaults: { _controller: App\Controller\SchedulesByYearController }
    requirements: { pid: '[0-9b-df-hj-np-tv-z]{8,15}', year: '\d{4}' }

# Redirect: /schedules/network/<network_url_key>   --->   /schedules/<default service pid in network>
schedules_by_network_url_key:
    path: /schedules/network/{networkUrlKey}
    defaults: { _controller: App\Controller\SchedulesByNetworkUrlKeyController }
    requirements: { networkUrlKey: '[a-zA-Z0-9]{2,35}' }

schedules_on_now:
    path: /schedules/network/{networkUrlKey}/on-now
    defaults: { _controller: App\Controller\SchedulesOnNowController }
    requirements: { networkUrlKey: '[a-zA-Z0-9]{2,35}' }

# Labs routes, for testing things

cloud_labs_root:
    path: /programmes/_cloudlabs
    defaults: { _controller: App\Controller\CloudLabsController, action: show }

cloud_labs:
    path: /programmes/_cloudlabs/{action}
    defaults: { _controller: App\Controller\CloudLabsController }

# Styleguide Amen

styleguide_amen_intro:
    path: /programmes/styleguide-amen
    defaults: { _controller: App\Controller\StyleguideAmenController::introAction }

styleguide_amen:
    path: /programmes/styleguide-amen/{action}
    defaults: { _controller: App\Controller\StyleguideAmenController, action: intro }

# Include any 3rd party routes. This should be the last thing in the file
_3rd_party:
    resource: routing_3rd_party.yml
