imports:
    - { resource: services.yml }
    - { resource: parameters.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # These are the default feed environments for LIVE. They may be overridden
    # on a per cosmos environment basis by editing config_prod_int.yml or
    # config_prod_test.yml
    app.feed_env.orbit: 'live'
    app.feed_env.branding: 'live'
    aws_s3_region: eu-west-1

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/config/routing.yml'
        strict_requirements: ~
    default_locale: '%locale%'
    trusted_hosts: ~
    http_method_override: false
    assets:
        base_path: 'assets'
    php_errors:
        log: true
    cache:
        pools:
            cache.programmes:
                # symfony support many adapters for different cache providers. cache.adapter.psr6 is a proxy adapter,
                # using cache.adapter.psr6 we can use any adapter class which implements the AdapterInterface
                adapter: 'cache.adapter.psr6'
                provider: '%cache_provider%'
                # the only aim of default_lifetime is to prevent setting permanent keys, please don't use the default_lifetime in the code.
                # PSR-6 consider "0" or NULL value as a way to store the key for as long as the implementation allows.
                default_lifetime: 120

# Twig Configuration
twig:
    date:
        timezone: Europe/London
    debug: '%kernel.debug%'
    exception_controller: App\Controller\ExceptionController
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/src/Ds2013': 'Ds2013'
        '%kernel.project_dir%/src/DsAmen': 'DsAmen'
        '%kernel.project_dir%/src/DsShared': 'DsShared'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                server_version: '%database_server_version%'
                charset: UTF8
        types:
            date_partial: BBC\ProgrammesPagesService\Data\ProgrammesDb\Type\DatePartialType
            datetime: BBC\ProgrammesPagesService\Data\ProgrammesDb\Type\UtcDateTimeType
            datetimetz: BBC\ProgrammesPagesService\Data\ProgrammesDb\Type\UtcDateTimeType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    ProgrammesPagesService:
                        type: annotation
                        dir: '%kernel.project_dir%/vendor/bbc/programmes-pages-service/src/Data/ProgrammesDb/Entity'
                        is_bundle: false
                        prefix: BBC\ProgrammesPagesService\Data\ProgrammesDb\Entity
                filters:
                    embargoed_filter:
                        class: BBC\ProgrammesPagesService\Data\ProgrammesDb\Filter\EmbargoedFilter
                        enabled: true
                dql:
                    string_functions:
                        MATCH_AGAINST: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\MatchAgainst
                        GROUP_CONCAT: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\GroupConcat
                    datetime_functions:
                        YEAR: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\Year
                        MONTH: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\Month
                        DAY: BBC\ProgrammesPagesService\Data\ProgrammesDb\Functions\Day

stof_doctrine_extensions:
    orm:
        default:
            tree: true
            timestampable: true

csa_guzzle:
    profiler: '%kernel.debug%'
    logger: true
    clients:
        default:
            alias: 'GuzzleHttp\ClientInterface'
            config:
                headers:
                    user-agent: 'bbc.co.uk-programmes/%cosmos_component_release% (%cosmos_environment%)'
                cert: '/etc/pki/dev.bbc.co.uk.pem'
                ssl_key: '/etc/pki/dev.bbc.co.uk.pem'
                verify: false
                timeout: 60
                connect_timeout: 10
