framework:
    cache:
        pools:
            cache.programmes:
                adapter: 'cache.adapter.psr6'
                provider: cache.null_provider
doctrine:
    dbal:
        connections:
            default:
                driver: pdo_mysql
                host: '%fixture_database_host%'
                port: '%fixture_database_port%'
                dbname: '%fixture_database_name%'
                user: '%fixture_database_user%'
                password: '%fixture_database_password%'
                server_version: '%database_server_version%'
                charset: UTF8
            fixture:
                driver: pdo_mysql
                host: '%fixture_database_host%'
                port: '%fixture_database_port%'
                dbname: '%scenario_database_name%'
                user: '%fixture_database_user%'
                password: '%fixture_database_password%'
                server_version: '%database_server_version%'
                charset: UTF8

    orm:
        entity_managers:
            fixture:
                connection: fixture
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Fixture:
                        type: annotation
                        dir: '%kernel.project_dir%/src/Fixture/Doctrine/Entity'
                        is_bundle: false
                        prefix: App\Fixture\Doctrine\Entity

stof_doctrine_extensions:
    orm:
        fixture:
            timestampable: true

services:
    # Fixture stuff
    App\EventSubscriber\FixtureSubscriber:
        autowire: true
        tags:
            - { name: 'kernel.event_subscriber', priority: 2048 }

    App\Fixture\Doctrine\EntityRepository\ScenarioRepository:
        factory: ["@doctrine.orm.fixture_entity_manager", getRepository]
        arguments:
            - App\Fixture\Doctrine\Entity\Scenario

    App\Fixture\Doctrine\EntityRepository\HttpFixtureRepository:
        factory: ["@doctrine.orm.fixture_entity_manager", getRepository]
        arguments:
            - App\Fixture\Doctrine\Entity\HttpFixture

    App\Fixture\ScenarioManagement\ScenarioState:
        public: true
        arguments:
            - '@App\ValueObject\CosmosInfo'
            - '@request_stack'
            - '%fixture_secure_key%'

    App\Fixture\ScenarioManagement\ScenarioManager:
        autowire: true

    App\Fixture\Guzzle\HttpFixtureMiddleware:
        arguments: ['@logger', '@App\Fixture\ScenarioManagement\ScenarioManager']
        tags:
            - { name: 'csa_guzzle.middleware', alias: 'http_fixture_middleware', pritority: 100 }

